### ISSUE TITLE
Add placeholder for Host IP adress

### ISSUE THREAD

**Issue by liorm0505** [hllhll/pyekonlib#2]
Should the configuration example look like this:

POST /config?command=client HTTP/1.1
User-Agent: LuaSocket 2.0.2
Content-Length: <content-length>
Content-Type: application/json; charset=utf-8
Host: <HVAC_unit_addr>

{"client_set":[{"ip":"<server_addr>","port":<server_udp_port>,"protocol":"UDP","local_port":80},{"protocol":"","ip":""},{"protocol":"","ip":""},{"protocol":"","ip":""}]}

**Comment by hllhll** [comment]
I'm not sure, the original app uses `Host: <ip address of the mobile device!>` and not the target,
I've successfully used just dummy 1.1.1.1

**Comment by hllhll** [comment]
I'm now more confident that it _**Wouldn't**_ work with the device address.

**Comment by liorm0505** [comment]
If that's the case, you can close the issue. 

Thanks,

**Comment by hllhll** [comment]
Just for documentation, It the Host address is probebly ignored, The device will mostly return `200 OK`. But will only actually implement the request if sent in a whole with **1 send()**. That's why no HTTP Library was used implementing https://github.com/hllhll/pyekonlib/commit/5628f407e190ce357bc95d78e42959a2d29f7002
